# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='uploader',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_quotes', to='quotes.User'),
            preserve_default=False,
        ),
    ]
