# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='liked_by_users',
            field=models.ManyToManyField(related_name='liked_quotes', to='quotes.User'),
        ),
    ]
